In [ ]:
#Creating array using  python list

arr=[1,2,3,4,5]

print(arr)
#Access elemnts from array
print(arr[0]," ",arr[4]," ")

#Modify elemsnts.
arr[1]=10
print(arr)

#Traversing array elements
for i in arr:
    print(i)

[1, 2, 3, 4, 5]
1   5  
[1, 10, 3, 4, 5]
1
10
3
4
5


In [12]:
#Using array module.

import array

arr=array.array('i',[10,20,30,40])
print(arr)

arr1=array.array('f',[10.2,20.3,0.4,0.45])
print(arr1)

array('i', [10, 20, 30, 40])
array('f', [10.199999809265137, 20.299999237060547, 0.4000000059604645, 0.44999998807907104])


Types code:
Code        DataTypes
i           Integer
f           Float
d           Double
b           Single char

In [40]:
from array import array
#Creation
arr1=array("i",[1,2,3,4,5]) #signed int array
arr2=array("f",[1.2,2.3,5.4]) #flat  array
arr3=array("d",range(10)) #double array

#print(arr1,arr2,arr3)

#Access (Same as list)
arr1[0]   # first elemn
arr1[-1]  #Last element
arr[1:3]  #Slicing -->retun new array

#Modifications
arr1[0]=24
arr1.append(6)
arr1.insert(0,0)
print(arr1)

# Removal
arr1.remove(3)   #remove first occurence
print(arr1)
arr1.pop()   # remove last
print(arr1)
arr1.pop(2) # remove at index
print(arr1)

# Info
arr3.typecode   # Type of array i,f,d
arr1.itemsize   # 4 (byte per element)
arr1.buffer_info() # Memory address length

#Converstion.
arr1.tolist() # arr to Python list
arr1.tobytes() # arr to bytes object

# Extend.
arr1.extend([7,8,9])  # from iterable
print(arr1)
arr1.fromlist([10,11]) # from list
print(arr1)

#Count /Index
arr1.count(4)  #Number of occurences.
arr1.index(5) #index of first occurences


# Reverse
arr1.reverse()
print(arr1)

array('i', [0, 24, 2, 3, 4, 5, 6])
array('i', [0, 24, 2, 4, 5, 6])
array('i', [0, 24, 2, 4, 5])
array('i', [0, 24, 4, 5])
array('i', [0, 24, 4, 5, 7, 8, 9])
array('i', [0, 24, 4, 5, 7, 8, 9, 10, 11])
array('i', [11, 10, 9, 8, 7, 5, 4, 24, 0])


In [ ]:
#Installing the numpy
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [61]:
# Using Numpy.

import numpy as np

#From data
arr=np.array([1,2,3]) # 1D
print(arr)
arr=np.array([[1,2],[3,4]]) # 2D
print(arr)
arr=np.array([1,2,3],dtype=np.float32) # Diffenrent type array
print(arr)

# Build -in creators
np.zeros((3,4))   # 3 *4 zeros
np.ones((2,3))   # 2*3 ones
np.full((3,3),8) # 3*3 filled with 8
np.eye(4)       # 4 * 4 Matrix
np.empty((2,2))  # uniniatlized (fast)

# Renges.
np.arange(0,10,2)   # [0,2,4,6,8] like range
np.linspace(0,1,5)  # 
np.logspace(0,2,3)

# Random.

np.random.rand(3,3)  #uniform[0,1)
np.random.randn(3,3) #standerd random values
np.random.randint(0,10,(3,3))  # random inits
np.random.choice([1,2,3,4],3)  # random sample
np.random.seed(42) # reproducabiity

[1 2 3]
[[1 2]
 [3 4]]
[1. 2. 3.]


In [ ]:
# Byte array and it's concept.

Byte array in Python : is a mutable sequence of bytes (numbers 0 to 255) used to store binary data .
Used when working with files,networking commucations,encriptions,images,low level data processing.


Byte array is a collection of bytes (8 bits integers)  ranges from 0 to 255.


In [63]:
#b = bytearray([10,20,30])
b = bytearray([65,66,67])
print(b)

bytearray(b'ABC')


In [64]:
b=bytes([65,66])
b[0]=70

TypeError: 'bytes' object does not support item assignment

Python has 2 binary data type:
Feature         bytes                 bytearray
Mutability      Immuatable            Mutable
Midification    Not possible          possible
Performence     Faster                slower
Usage           Fixed binary data     Editable binary data

In [68]:
#Create Byte Arrays:
#Method 1: from List of integers.
b=bytearray([10,20,30,40])
print(b)
#Method 2:From string
b=bytearray("hello","utf-8")
print(b)
#Method 3: With sixe initialization.
b=bytearray(5)
print(b)
#Method 4: From bytes.
b=bytearray(b"python")
print(b)

bytearray(b'\n\x14\x1e(')
bytearray(b'hello')
bytearray(b'\x00\x00\x00\x00\x00')
bytearray(b'python')


In [73]:
b=bytearray([10,20,30,40])
print(b)

#Accesiing Elements.
print(b[0])
print(b[-1])

#Modification : Mutable so possible
b[0]=50
print(b[0])

#Slicing allowed .
b=bytearray(b"python")
print(b[1:4])

bytearray(b'\n\x14\x1e(')
10
40
50
bytearray(b'yth')


In [78]:
# Supported / common methods.
b=bytearray([65,66])
b.append(67) #Single element append
b.extend([68,69]) #Add multiple bytes.
b.insert(1,70) #Inserting values directing.
b.remove(70) # General removed based on value
b.pop() # remove last element
print(b)

bytearray(b'ABCD')


In [79]:
b=bytearray(b"hello")
b.clear()

print(b)

bytearray(b'')


In [ ]:
# Convertions:
#Bytearray to String.
b =bytearray(b"hello")
s=b.decode("utf-8")
print(s)
#String to byte array
s="hello"
b=bytearray(s,"utf-8")
print(b)
#Bytearray to lst
b = bytearray(b"ABC")
#Iterating byte array
#print(list(b))
for i in b:
    print(b)

hello
bytearray(b'hello')
bytearray(b'ABC')
bytearray(b'ABC')
bytearray(b'ABC')


Bytearray vs list.

feature    bytearray         list
Elemnts    0-255 only        Any object
Mem        Efficient        Larger
Mutablity  Mutable          Mutable
Binarydat  Ideal            Not ideal

A byttearray in python is mutable sequence of bytes used for efficient binay data manipulations.

Commonly used in file handling,networking,encrption and other low level data processing.